### ISSUE TITLE
Code Citation - DOI

### ISSUE THREAD

**Issue by mozhgan-kch** [FLAMEGPU/FLAMEGPU2#19]
A suggestion: assign a DOI to the repo to be able to cite it in papers.
[https://guides.github.com/activities/citable-code/](https://guides.github.com/activities/citable-code/)

**Comment by ptheywood** [comment]
See flamegpu/flamegpu#251

**Comment by ptheywood** [comment]
https://twitter.com/natfriedman/status/1420122675813441540

![image](https://user-images.githubusercontent.com/628937/127230682-726c9303-315a-4443-9574-80c8d18fdbce.png)

https://citation-file-format.github.io/

**Comment by Robadob** [comment]
Good find, have added it to newswire too.

**Comment by ptheywood** [comment]
https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md#definitionspersonalias

**Comment by ptheywood** [comment]
Zenodo's github integration only seems to apply for non pre-releases (looks like people were annoyed that all pre-releases were getting DOI'd, which probably makes sense in general. 

Otherwise if you log into zenodo via github OAuth then that is how access is managed, so no need to worry about account credentials or anything, just anyone with presumably org permissions can manage the zenodo going forwards.

**Comment by ptheywood** [comment]
From the [Zenodo FAQ](https://help.zenodo.org):

> ### I made a GitHub release, but it does not show up on Zenodo.
>
> Make sure the repository was enabled before the release was made, otherwise feel free to contact us.

I think I enabled zenodo *after* creating the release (I might be wrong) so that might be why the releases haven't shown up (unless it is because they are pre-releases as mentioned above). We could potentially cheese this if required by publishing a future pre-release as not a pre-release on github, then edit it back to a pre-release if this is the case?

**Comment by ptheywood** [comment]
After pushing `v2.0.1-alpha.1` and creating the release, the GitHub integration with zenodo fired, and produced a DOI. 

I'll make a PR to add generic zenodo related info to the readme and citation.cff file now that it exists.

### DOIs / URIs

Zenodo provides a Generic DOI for a project which will alwasy resolve to the latest version

It also provides a per-release DOI, to uniquely identify individual releases.

+ Generic URI:  https://zenodo.org/record/5428984
+ Generid DOI [10.5281/zenodo.5428984](https://doi.org/10.5281/zenodo.5428984)

+ `2.0.0-alpha.1` URI:  https://zenodo.org/record/5428985
+ `2.0.0-alpha.1 DOI: [10.5281/zenodo.5428985](https://doi.org/10.5281/zenodo.5428985)

### Zenodo Account(s)

Users with GitHub write(?) access to this repository can control the Zenodo settings for this repository

+ [Sign up](https://zenodo.org/signup/) using GitHub OAuth
+ Log in
+ Go to the github account settings page: https://zenodo.org/account/settings/github/
+ Select `FLAMEGPU/FLAMEGPU2` from the list of enabled repositories
