### ISSUE TITLE
MsgArray2D CUDA error with dimension/population mismatch

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU2#242]
Using a `MsgArray2D` with dimensions greater than the number of agents results in a CUDA error beign thrown, rather than an appropriate error prior to execution.

E.g. modifying he Game Of life Example with fewer agents will crash during the first iteration.

```
const unsigned int SQRT_AGENT_COUNT = 4;
```

+ [ ] Implement tests to check for matching/mismatching agent populations and message dimensions
+ [ ] Implement runtime checks which throw appropriate exceptions
+ [ ] Adjust Game Of Life example to use a common variable for message dimensions and dynamic population.

This also suggets that it is not possible to have optional MsgArray2D output? Is this intended?

**Comment by Robadob** [comment]
Optional should be possible, as i recall it just leaves the message uninitialised (there's no, message has been written flag). So if user reads it, they get 0 (we dont have a graceful error anyway)

**Comment by Robadob** [comment]
There's an optional test, but it just means some agent's don't output.

https://github.com/FLAMEGPU/FLAMEGPU2_dev/blob/master/tests/test_cases/runtime/messaging/test_array_2d.cu#L101

**Comment by ptheywood** [comment]
I only stumbled across this while using the Game of life example wile figuring out the interface for id access by accident, with `message.setDimensions(10, 10);` and `const unsigned int SQRT_AGENT_COUNT = 4;`, so `36/100` messages are being set by a compulsory message output. It must  just be falling foul of something not checked during compulsory output (i assume, not investigated)

```
terminate called after throwing an instance of 'CUDAError'
  what():  /home/ptheywood/code/flamegpu/flamegpu2_dev/include/flamegpu/gpu/CUDAErrorChecking.h(26): CUDA Error: /home/ptheywood/code/flamegpu/flamegpu2_dev/src/flamegpu/runtime/messaging/Array2D.cu(93): invalid argument
Aborted (core dumped)
```

**Comment by Robadob** [comment]
`flamegpu/runtime/messaging/Array2D.cu:93` is where it errors (I'm looking into it now).

Appears to be because the output message arrays are sized based on agent count, rather than message count (other messaging types don't have a message count iirc). Swapping `hd_metadata.length` for `MESSAGE_COUNT`  on that line should fix.

**Comment by Robadob** [comment]
`this->sim_message.getMaximumListSize()` is the better option actually, as comment states message array may be longer than message count.

**Comment by Robadob** [comment]
None of that will work anyway.
Eventually it's all passed to `CUDAScatter::arrayMessageReorder()`, which requires the message array be the right length.

In summary, the actual issue is:
* CUDAMessage is only resized at message output time, to the agent state size (unless message append is enabled because multiple output during a step).
* When 'buildIndex()` is called, we have N out of order messages in one buffer, and need to write it to ordered buffer, which requires length M. In array messaging these two values are independent.

Solution is to add an init method to CUDAMessageHandler(), so array messages can resize() to minimum array size at the start.

I have some queries about how Array messages will handle the append/truncate though. Given it's not a traditional message list.

**Comment by Robadob** [comment]
Is this related to the array msg bug you fixed the other week? (#736)

**Comment by ptheywood** [comment]
The method of reproducing defned above (16 agents, 100 bins) does run successfully now that may have been the actual problem, though the cuda error reported above was in the message class not in the Reorder function (although this could have just been due to a missing sync/error code check in the past that has since been corrected. 

There is still a TODO comment about checkign for errors in MessageArray2D at what might have been the preivous location of the CUDAError (thoughit might have been moved aorund a fair bit since then)

https://github.com/FLAMEGPU/FLAMEGPU2/blob/ae59d08c1bf779da5eede759d50bf2f10fbc56a7/src/flamegpu/runtime/messaging/MessageArray2D.cu#L92-L93 

Might be safe to close this for now given the above doesn't reproduce the error anymore?

**Comment by Robadob** [comment]
Detecting errors may have already been covered, in earlier passes where missing `CUDA_CALL` were added, so yes It can be probably be assumed fixed unless it rises again.
