### ISSUE TITLE
Import pyflamegpu error

### ISSUE THREAD

**Issue by khateraAlizada** [FLAMEGPU/FLAMEGPU2#953]
**Describe the bug**
When I try to  import pyflamegpu in the template model link below, it gives error (below) can not import pyflamegpu. How can I resovle the issue :
https://colab.research.google.com/github/FLAMEGPU/FLAMEGPU2-tutorial-python/blob/google-colab/FLAME_GPU_2_python_tutorial.ipynb#scrollTo=xd8iL5XniTnb

ImportError                               Traceback (most recent call last)
[<ipython-input-15-691bee62c3ad>](https://localhost:8080/#) in <module>
      6 # Import pyflamegpu and some other libraries we will use in the tutorial
      7 sys.path.append(os.path.expanduser('~') + "/.local/lib/python3.6/site-packages")
----> 8 import pyflamegpu
      9 import sys, random, math
     10 import matplotlib.pyplot as plt

1 frames
[/usr/local/lib/python3.7/dist-packages/pyflamegpu/pyflamegpu.py](https://localhost:8080/#) in <module>
     11 # Import the low-level C/C++ module
     12 if __package__ or "." in __name__:
---> 13     from . import _pyflamegpu
     14 else:
     15     import _pyflamegpu

ImportError: libnvrtc.so.11.0: cannot open shared object file: No such file or directory
**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**
If applic
<img width="1440" alt="Screen Shot 2022-10-29 at 7 48 48 AM" src="https://user-images.githubusercontent.com/20228364/198829893-1c142194-f022-4e74-aa39-fee2d270a3b0.png">
[able,] add screenshots to help explain your problem.

**Configuration(please complete the following information):**
 - OS: [e.g. Ubuntu 16.04, Windows 10]
 - CUDA version: [e.g. 11.0]
 - GPU [e.g. Titan X (Pascal)]
 - GPU Driver Version [e.g. 445.75]

**Additional context**

**Comment by Robadob** [comment]
Thanks for raising this.

This appears to be because Google Collab has updated the version of CUDA installed (@mondus [mentioned this](https://github.com/FLAMEGPU/FLAMEGPU2/issues/605#issuecomment-1293478564) a couple of days ago. Therefore it's necessary to use a wheel built for CUDA 11.2+ instead.

If you change the second line of the collab to this it should work (however there might be some breaking changes with this newer wheel).
```
!{sys.executable} -m pip install -I https://github.com/FLAMEGPU/FLAMEGPU2/releases/download/v2.0.0-alpha.2/pyflamegpu-2.0.0a2+cuda112-cp37-cp37m-linux_x86_64.whl
```

I've created a PR [here](https://github.com/FLAMEGPU/FLAMEGPU2-tutorial-python/pull/17/files) with the change, which when merged (hopefully during next week, after we've had a chance to check for breaking changes) should update the main tutorial so you don't have to make this change yourself.

**Comment by Robadob** [comment]
Hi, I've just pushed the updated wheel to Colab so this should now be resolved automatically when you visit https://flamegpu.com/try. Please let us know if you have any further problems.

**Comment by khateraAlizada** [comment]
Hello,
I am trying to develop a model in pyflame gpu. I need some help with coding
python functions. Is there any ways I can get some help.

thank you ,
Khatera

**Comment by khateraAlizada** [comment]
Hello,
I am trying to develop a model in pyflame gpu. I need some help with coding
python functions. Is there any ways I can get some help.

thank you ,
Khatera

**Comment by Robadob** [comment]
> I am trying to develop a model in pyflame gpu. I need some help with coding
python functions. Is there any ways I can get some help.

You can create topics on https://github.com/FLAMEGPU/FLAMEGPU2/discussions for more general support with using FLAME GPU.
